import { test, expect } from '@playwright/test';
import { uiLoginAsAdmin, uiLoginAsStudent } from './helpers/ui-auth.js';

const ADMIN_EMAIL = 'admin@staysphere.com';
const ADMIN_PASSWORD = 'password123';
const STUDENT_EMAIL = 'student@staysphere.com';
const STUDENT_PASSWORD = 'password123';

test.describe('Complaints Module', () => {
  
  test.beforeEach(async ({ page }) => {
    // Mock Login
    await page.route('**/api/auth/login', async route => {
      const body = route.request().postDataJSON();
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          token: 'fake-token',
          name: body.role === 'Student' ? 'John Student' : 'Super Admin',
          email: body.email,
          role: body.role
        })
      });
    });

    // Mock Complaints GET
    await page.route('**/api/complaints', async route => {
      if (route.request().method() === 'GET') {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify([
            {
              _id: '1',
              category: 'Electrical',
              title: 'Light not working',
              description: 'The light in room 101 is flickering.',
              locationType: 'room',
              roomNumber: '101',
              status: 'Pending',
              createdAt: new Date().toISOString(),
              displayName: 'John Student'
            }
          ])
        });
      } else if (route.request().method() === 'POST') {
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({ message: 'Complaint submitted successfully' })
        });
      }
    });

    // Mock Complaints MY
    await page.route('**/api/complaints/my', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([
          {
            _id: '1',
            category: 'Electrical',
            title: 'Light not working',
            description: 'The light in room 101 is flickering.',
            locationType: 'room',
            roomNumber: '101',
            status: 'Pending',
            createdAt: new Date().toISOString(),
            displayName: 'John Student'
          }
        ])
      });
    });

    // Mock Complaint PUT
    await page.route('**/api/complaints/admin/*', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ message: 'Updated' })
      });
    });
  });

  test('Student can submit a complaint', async ({ page }) => {
    // Login as student
    await uiLoginAsStudent(page, STUDENT_EMAIL, STUDENT_PASSWORD);
    
    await page.goto('/student-file-complaint');
    
    // Check if we are on the right page
    await expect(page.getByText('Submit your request with confidence')).toBeVisible();
    
    // Fill the form
    await page.selectOption('select >> nth=0', 'room');
    await page.selectOption('select >> nth=1', 'Electrical');
    await page.selectOption('select >> nth=2', '1'); // Floor 1
    await page.selectOption('select >> nth=3', '101'); // Room 101
    
    const title = `Test Complaint ${Date.now()}`;
    await page.fill('input[placeholder="Brief description of the issue"]', title);
    await page.fill('textarea[placeholder="Provide full details about the issue..."]', 'This is a test complaint description generated by Playwright.');
    
    // Submit
    await page.click('button:has-text("Submit Complaint")');
    
    // Verify success
    await expect(page.getByText('Complaint submitted successfully')).toBeVisible();
    
    // Verify in "My Complaints"
    await page.click('button:has-text("View My Complaints")');
    await expect(page).toHaveURL(/.*student-complaints/);
    // Since we mock the list, we verify the mocked list contains a complaint
    await expect(page.getByText('Light not working')).toBeVisible();
  });

  test('Admin can manage complaints', async ({ page }) => {
    // Login as admin
    await uiLoginAsAdmin(page, ADMIN_EMAIL, ADMIN_PASSWORD);
    
    await page.goto('/admin-complaints');
    
    // Check if we are on the right page
    await expect(page.getByText('Complaints & Maintenance Management').first()).toBeVisible();
    
    // Find a pending complaint (the one we mocked)
    const complaintRow = page.locator('tr').filter({ hasText: 'Pending' }).first();
    
    await expect(complaintRow).toBeVisible();
    
    // Assign worker
    await complaintRow.locator('input[placeholder="Assign Worker"]').fill('John Mechanic');
    await complaintRow.locator('button:has-text("Save assignment")').click();
    
    // Mark as done
    await complaintRow.locator('button:has-text("Mark Done")').click();
    
    // Verify UI logic (the status changes in UI after refresh or update)
    // In our mock, we just return 200, so we check if the button was clicked
  });


  test('Room validation logic works correctly', async ({ page }) => {
    await uiLoginAsStudent(page, STUDENT_EMAIL, STUDENT_PASSWORD);
    await page.goto('/student-file-complaint');
    
    // Select floor 1
    await page.selectOption('select >> nth=2', '1');
    
    // Check if room options are correct for floor 1
    const roomSelect = page.locator('select >> nth=3');
    const options = await roomSelect.locator('option').allTextContents();
    expect(options).toContain('Room 101');
    expect(options).not.toContain('Room 106'); // 106 is floor 2
    
    // Change to floor 2
    await page.selectOption('select >> nth=2', '2');
    const options2 = await roomSelect.locator('option').allTextContents();
    expect(options2).toContain('Room 106');
    expect(options2).not.toContain('Room 101');
  });
});
